# config/services.yaml

parameters:
    # Paramètres globaux (optionnel)
    # app_secret: '%env(APP_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # -------------------------------
    # AccountDeletionService
    # -------------------------------
    App\Service\AccountDeletionService:
        autowire: false  # Désactive l'autowire pour ce service
        arguments:
            $appSecret: '%env(APP_SECRET)%'  # Injection explicite de la string

    # -------------------------------
    # LoginAuthenticator
    # -------------------------------
    App\Security\LoginAuthenticator:
        arguments:
            $urlGenerator: '@router.default'  # Service Symfony qui implémente UrlGeneratorInterface

    # -------------------------------
    # EmailVerifier
    # -------------------------------
    App\Security\EmailVerifier:
        arguments:
            $verifyEmailHelper: '@verify_email.helper'
            $mailer: '@mailer.mailer'        # ou '@mailer' selon ta version de Symfony
            $entityManager: '@doctrine.orm.entity_manager'

    # -------------------------------
    # Autres services automatiques
    # -------------------------------
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Service/AccountDeletionService.php}'
        # On exclut uniquement AccountDeletionService pour éviter les conflits d'autowire
